### ISSUE TITLE
Les cerques no retornen resultats

### ISSUE THREAD

**Issue by tgaya-dgtic** [GovernIB/pluginsib-arxiu#47]
Les cerques, per exemple emprant documentConsulta fallen perquè a la petició searchDocsRequest cap a GDIB especificau
               `<pageNumber>1</pageNumber>`
I això no retorna resultats.

Ho haurieu de substituir per
               `<pageNumber>0</pageNumber>`

(Si no s'indica aquest paràmetre, també va bé)

**Comment by josepg-limit** [comment]
El paràmetre _pageNumber_ s'informa a partir del paràmetre d'entrada _pagina_ del mètode _documentConsultar_.
