### ISSUE TITLE
Strings continguts als camps de metadades

### ISSUE THREAD

**Issue by santich-dgtic** [GovernIB/pluginsib-arxiu#54]
S'hauria de remplaçar per la cadena buida les ocurrències dels caràcters \n, \t, cometes dobles i cometes simples, als camps de metadades, ja que això fa que, quan per exemple hi ha un d'aquests caràcters en el nom del fitxer, no se parsetgi bé al bus de serveis i acabi amb error

**Comment by tgaya-dgtic** [comment]
Sobretot el canvi imprescindible és que el camp que queda a dins Arxiu com a "cm:name" només pugui contenir els caràcters que pot tenir un nom de fitxer a damunt un sistema de fitxers qualsevol.

És a dir, lletres i números, caràcter guió baix (_), caràcter guió (-), i espais enmig (no pot contenir espais tant al principi com al final. Se li hauria d'aplicar una funció trim()).
