### ISSUE TITLE
Mètode getCSV no funciona: retorna null

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib-arxiu#68]
Mètode getCSV no funciona: retorna null.

Resulta que intenta obtenir el CSV dels documents signats, però pareix que en algun moment donat el CSV va desaparèixer de les signatures del Document. Ho hauria d'obtenir de les Metadades dels Document

**Comment by tgaya-dgtic** [comment]
Només com a comentari,
Si un document està signat i és esborrany, no toca tenir csv (se toca retornar null).
El csv només el toquen tenir els documents signats i marcats com a definitius.

**Comment by tgaya-dgtic** [comment]
Toni, podries comprovar si l'error era el que jo he comentat jo, en tal cas tancaríem la incidència? Gràcies.
