### ISSUE TITLE
Confusió entre propietat "plugin.arxiu.caib.csv.definicio" i "plugin.arxiu.caib.csv_generation_definition"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/pluginsib-arxiu#69]
En el plugin d'ArxiuCaib hi ha dos mètodes per obtenir la ruta al document on es descriu com es genera el CSV

(1) public String getCsvGenerationDefinition(String identificadorDoc) throws ArxiuException;
(2) public String getCsvGenerationDefinition(ContingutArxiu doc) throws ArxiuException;

El problema està en que pel primer s'utilitza la propietat "plugin.arxiu.caib.csv_generation_definition" i pel segon la propietat "plugin.arxiu.caib.csv.definicio".

(a) Fer que s'empre usi la propietat "plugin.arxiu.caib.csv_generation_definition"
(b) Fer check de que si existeix la propietat "plugin.arxiu.caib.csv.definicio" llavors llançar una excepció indicant que s'ha de canvia per "plugin.arxiu.caib.csv_generation_definition".

**Comment by tgaya-dgtic** [comment]
Si no record malament, aquests mètodes els vareu proposar vosaltres.
Per evitar que estem bloquejats per aquest tema, ens podeu passar la llista de canvis? Gràcies.

**Comment by anadal-fundaciobit** [comment]
Bones:

     Adjunt els canvis en format .patch i els documents originals (lis he hagut de posar extensió .txt)

     Qualsevol problema em deis coses.



[isuue69.patch.txt](https://github.com/GovernIB/pluginsib-arxiu/files/9697747/isuue69.patch.txt)



[ArxiuPluginCaib.java.txt](https://github.com/GovernIB/pluginsib-arxiu/files/9697742/ArxiuPluginCaib.java.txt)
[plugin.properties.sample.txt](https://github.com/GovernIB/pluginsib-arxiu/files/9697743/plugin.properties.sample.txt)
